name: ume_talk
description: Chat App.

version: 1.0.5+15

environment:
  sdk: ">=2.15.0-233.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.2.0
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.3.0
  cloud_firestore: ^3.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.9
  firebase_storage: ^10.1.0
  cached_network_image: ^3.1.0+1
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  photo_view: ^0.13.0
  cupertino_icons: ^1.0.4
  auto_size_text: ^3.0.0
  new_version: ^0.2.3
  rxdart: ^0.27.3
  image_gallery_saver: ^1.7.1
  dio: ^4.0.4
  flutter_app_badger: ^1.3.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0


flutter:
  uses-material-design: true
  assets:
    - images/
